### PR TITLE
adds support for legacy-peer-deps flag on npm install

### PR DESCRIPTION
**Pull request by MiniDigger**
https://github.com/dylang/npm-check/pull/424

### CODE REVIEW

**Comment by Nefcanto** [comment]
How does it work?

**Comment by MiniDigger** [comment]
npx npm-check-updated -u --legacy-peer-deps

**Comment by Nefcanto** [comment]
@MiniDigger so that the command is changed from `npm-check` to `npm-check-updated`. Is that a good decision? Why not having the original command?

**Comment by Nefcanto** [comment]
@MiniDigger I got this error:

```
Need to install the following packages:
npm-check-updated@6.0.4
Ok to proceed? (y) y
⠦ Checking npm registries for updated packages.Invalid Version: 2021.08.30
For more detail, add `--debug` to the command
```

**Comment by MiniDigger** [comment]
> For more detail, add `--debug` to the command

**Comment by MiniDigger** [comment]
> @MiniDigger so that the command is changed from `npm-check` to `npm-check-updated`. Is that a good decision? Why not having the original command?

I dont control the original repo, I just forked it for my own usage

**Pull request merged**
